import { Patient, MedicalReport, TestResult } from './types';
import { evaluateTestStatus } from './evaluator';

export const SAMPLE_PATIENTS: Patient[] = [
  {
    id: 'PT-89421',
    name: 'John Doe',
    age: 54,
    sex: 'Male',
    symptoms: ['Mild Fatigue', 'Increased Thirst', 'Occasional Blurred Vision'],
    existingConditions: ['Type 2 Diabetes Mellitus', 'Essential Hypertension', 'Hyperlipidemia'],
    allergies: ['Penicillin'],
    currentMedications: ['Metformin 500mg (BID)', 'Lisinopril 10mg (QD)', 'Atorvastatin 20mg (QD)'],
    lastUpdated: '2026-09-02',
  },
  {
    id: 'PT-33104',
    name: 'Sarah Jenkins',
    age: 32,
    sex: 'Female',
    symptoms: ['Severe Fatigue', 'Dizziness', 'Cold Sensitivity', 'Shortness of Breath on Exertion'],
    existingConditions: [], // None listed - triggers conflict when anemia lab comes in!
    allergies: ['No Known Drug Allergies (NKDA)'], // Triggers conflict when report notes Amoxicillin rash!
    currentMedications: ['Over-the-counter Multivitamin'],
    lastUpdated: '2026-09-04',
  },
  {
    id: 'PT-51299',
    name: 'Marcus Vance',
    age: 68,
    sex: 'Male',
    symptoms: ['Bilateral Knee Pain', 'Morning Joint Stiffness'],
    existingConditions: ['Osteoarthritis'],
    allergies: ['Sulfa Drugs'],
    currentMedications: ['Celecoxib 100mg (QD)'],
    lastUpdated: '2026-08-28',
  }
];

export const SAMPLE_TEST_RESULTS_PATIENT_1_CURRENT: TestResult[] = [
  {
    id: 'tr-101',
    testName: 'Fasting Blood Glucose',
    value: 138,
    unit: 'mg/dL',
    referenceRange: '70 - 99',
    status: evaluateTestStatus(138, '70 - 99'),
    date: '2026-09-02',
    observations: 'Patient fasted for 10 hours prior to venipuncture.',
    provenance: 'Medical Report',
    confidence: 98,
    category: 'Metabolic',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-102',
    testName: 'Hemoglobin A1c (HbA1c)',
    value: 7.4,
    unit: '%',
    referenceRange: '4.0 - 5.6',
    status: evaluateTestStatus(7.4, '4.0 - 5.6'),
    date: '2026-09-02',
    observations: 'Glycated hemoglobin reflects elevated 90-day mean glucose.',
    provenance: 'Medical Report',
    confidence: 96,
    category: 'Metabolic',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-103',
    testName: 'Total Cholesterol',
    value: 215,
    unit: 'mg/dL',
    referenceRange: '< 200',
    status: evaluateTestStatus(215, '< 200'),
    date: '2026-09-02',
    observations: 'Lipid profile extracted from serum sample.',
    provenance: 'Medical Report',
    confidence: 99,
    category: 'Lipids',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-104',
    testName: 'LDL Cholesterol',
    value: 134,
    unit: 'mg/dL',
    referenceRange: '< 100',
    status: evaluateTestStatus(134, '< 100'),
    date: '2026-09-02',
    observations: 'Calculated using Friedewald equation.',
    provenance: 'Medical Report',
    confidence: 95,
    category: 'Lipids',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-105',
    testName: 'HDL Cholesterol',
    value: 46,
    unit: 'mg/dL',
    referenceRange: '> 40',
    status: evaluateTestStatus(46, '> 40'),
    date: '2026-09-02',
    observations: 'Protective high-density lipoprotein level.',
    provenance: 'Medical Report',
    confidence: 97,
    category: 'Lipids',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-106',
    testName: 'Triglycerides',
    value: 185,
    unit: 'mg/dL',
    referenceRange: '< 150',
    status: evaluateTestStatus(185, '< 150'),
    date: '2026-09-02',
    observations: 'Elevated serum triglycerides.',
    provenance: 'Medical Report',
    confidence: 98,
    category: 'Lipids',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-107',
    testName: 'Hemoglobin',
    value: 14.5,
    unit: 'g/dL',
    referenceRange: '13.5 - 17.5',
    status: evaluateTestStatus(14.5, '13.5 - 17.5'),
    date: '2026-09-02',
    observations: 'Complete Blood Count sub-parameter.',
    provenance: 'Medical Report',
    confidence: 99,
    category: 'Hematology',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-108',
    testName: 'White Blood Cell (WBC)',
    value: 6.8,
    unit: 'K/uL',
    referenceRange: '4.5 - 11.0',
    status: evaluateTestStatus(6.8, '4.5 - 11.0'),
    date: '2026-09-02',
    observations: 'Normal white blood cell count.',
    provenance: 'Medical Report',
    confidence: 99,
    category: 'Hematology',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-109',
    testName: 'Serum Creatinine',
    value: 1.05,
    unit: 'mg/dL',
    referenceRange: '0.70 - 1.30',
    status: evaluateTestStatus(1.05, '0.70 - 1.30'),
    date: '2026-09-02',
    observations: 'Normal kidney filtration marker.',
    provenance: 'Medical Report',
    confidence: 98,
    category: 'Renal',
    verifiedByHuman: true,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-110',
    testName: 'Vitamin D (25-Hydroxy)',
    value: 19.2,
    unit: 'ng/mL',
    referenceRange: null, // STRICT RULE: NO REFERENCE RANGE IN REPORT!
    status: evaluateTestStatus(19.2, null), // Must output CANNOT DETERMINE!
    date: '2026-09-02',
    observations: 'Reference range omitted in lab scan output.',
    provenance: 'Medical Report',
    confidence: 88,
    category: 'Endocrine',
    verifiedByHuman: false,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  },
  {
    id: 'tr-111',
    testName: 'High Sensitivity CRP',
    value: 3.1,
    unit: 'mg/L',
    referenceRange: null, // STRICT RULE: NO REFERENCE RANGE IN REPORT!
    status: evaluateTestStatus(3.1, null), // Must output CANNOT DETERMINE!
    date: '2026-09-02',
    observations: 'Inflammatory marker present without laboratory reference bounds.',
    provenance: 'Medical Report',
    confidence: 85,
    category: 'Cardiovascular',
    verifiedByHuman: false,
    reportId: 'REP-2026-0902',
    reportName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
  }
];

export const SAMPLE_TEST_RESULTS_PATIENT_1_HISTORICAL: TestResult[] = [
  {
    id: 'tr-101-h',
    testName: 'Fasting Blood Glucose',
    value: 122,
    unit: 'mg/dL',
    referenceRange: '70 - 99',
    status: evaluateTestStatus(122, '70 - 99'),
    date: '2026-03-10',
    observations: 'Previous spring checkup baseline.',
    provenance: 'Medical Report',
    confidence: 97,
    category: 'Metabolic',
    verifiedByHuman: true,
    reportId: 'REP-2026-0310',
    reportName: 'Spring_Routine_Labs.pdf',
  },
  {
    id: 'tr-102-h',
    testName: 'Hemoglobin A1c (HbA1c)',
    value: 6.8,
    unit: '%',
    referenceRange: '4.0 - 5.6',
    status: evaluateTestStatus(6.8, '4.0 - 5.6'),
    date: '2026-03-10',
    observations: 'Baseline HbA1c prior to dosage adjustment.',
    provenance: 'Medical Report',
    confidence: 98,
    category: 'Metabolic',
    verifiedByHuman: true,
    reportId: 'REP-2026-0310',
    reportName: 'Spring_Routine_Labs.pdf',
  },
  {
    id: 'tr-103-h',
    testName: 'Total Cholesterol',
    value: 198,
    unit: 'mg/dL',
    referenceRange: '< 200',
    status: evaluateTestStatus(198, '< 200'),
    date: '2026-03-10',
    observations: 'Normal baseline total cholesterol.',
    provenance: 'Medical Report',
    confidence: 98,
    category: 'Lipids',
    verifiedByHuman: true,
    reportId: 'REP-2026-0310',
    reportName: 'Spring_Routine_Labs.pdf',
  }
];

export const SAMPLE_REPORTS: MedicalReport[] = [
  {
    id: 'REP-2026-0902',
    title: 'Quest Diagnostics Comprehensive Metabolic & Lipid Panel',
    fileName: 'Quest_Diagnostics_Comprehensive_Panel.pdf',
    fileSize: '1.4 MB',
    uploadDate: '2026-09-02',
    reportDate: '2026-09-02',
    labName: 'Quest Diagnostics Regional Lab #402',
    extractedCount: 11,
    status: 'Processed',
    tests: SAMPLE_TEST_RESULTS_PATIENT_1_CURRENT,
  },
  {
    id: 'REP-2026-0310',
    title: 'Spring Routine Health Checkup Panel',
    fileName: 'Spring_Routine_Labs.pdf',
    fileSize: '890 KB',
    uploadDate: '2026-03-10',
    reportDate: '2026-03-10',
    labName: 'Metropolitan Health Clinical Labs',
    extractedCount: 3,
    status: 'Processed',
    tests: SAMPLE_TEST_RESULTS_PATIENT_1_HISTORICAL,
  }
];
